# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: install sdk
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    command: 'build'
    projects: 'pipelines-dotnet-core/pipelines-dotnet-core.csproj'
    workingDirectory: 'pipelines-dotnet-core'
- task: DotNetCoreCLI@2
  displayName: dotnet run
  inputs:
    command: 'run'
    projects: 'pipelines-dotnet-core/pipelines-dotnet-core.csproj'
    workingDirectory: 'pipelines-dotnet-core'
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: 'pipelines-dotnet-core/pipelines-dotnet-core.csproj'
- task: DotNetCoreCLI@2
  displayName: publish artifact
  inputs:
    command: 'publish'
    publishWebProjects: true